export const URLS = {
  SETTINGS: '/settings',
  HOME_SECTIONS: '/homeSections',
  CONTACT: '/contact',
  COUNTRIES: '/countries',
  CITIES: '/countries/:country/cities',
  LANGUAGES: '/languages',
  GENDERS: '/genders',
  CATEGORIES: '/categories',
  POST_TYPES: '/postTypes',
  PAGES: '/pages',
  PICTURES: '/pictures',
  REPORT_TYPES: 'reportTypes',
  REPORT_POST: '/posts/{id}/report',
  POSTS: '/posts',
  THREADS: '/threads',
  THREAD_MESSAGES: '/threads/:id/messages',
  THREADS_BULK: '/threads/bulkUpdate/:ids',
  SAVED_POSTS: '/savedPosts',
  SAVED_SEARCHES: '/savedSearches',
  PAYMENTS: '/payments',
  AUTH_REGISTER: '/auth/register',
  AUTH_LOGIN: '/auth/login',
  AUTH_PASSWORD_EMAIL: '/auth/password/email',
  AUTH_LOGOUT: '/auth/logout',
  USERS: '/users',
  USERS_ID: '/users/:id'
}
